services:
  # WordPress test environment
  wordpress-test:
    image: arm64v8/php:8.0-cli
    volumes:
      - .:/var/www/html/wp-content/plugins/thrive-leads-mailcoach-integration
    working_dir: /var/www/html/wp-content/plugins/thrive-leads-mailcoach-integration
    depends_on:
      - mysql
    environment:
      - WP_TESTS_DB_HOST=mysql
      - WP_TESTS_DB_NAME=wordpress_test
      - WP_TESTS_DB_USER=root
      - WP_TESTS_DB_PASSWORD=rootpassword
      - WP_TESTS_DB_PORT=3306
      - WP_TESTS_DIR=/tmp/wordpress-tests-lib
    command: >
      bash -c "
        apt-get update && apt-get install -y git subversion default-mysql-client unzip wget
        && php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\"
        && php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        && php -r \"unlink('composer-setup.php');\"
        && docker-php-ext-install mysqli pdo pdo_mysql
        && composer install --no-interaction
        && mkdir -p /tmp/wordpress-tests-lib
        && bash bin/install-wp-tests.sh wordpress_test root rootpassword mysql latest
        && echo 'WordPress test environment is ready. Run tests with: docker-compose exec wordpress-test ./vendor/bin/phpunit'
        && tail -f /dev/null
      "

  # MySQL database for tests
  mysql:
    image: arm64v8/mysql:oracle
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress_test
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  # PhpMyAdmin - optional utility to view the database
  phpmyadmin:
    image: arm64v8/phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"

volumes:
  mysql_data: