name: Plugin Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: WordPress Latest on PHP 8.3

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, pdo_mysql
        coverage: xdebug

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y subversion

    - name: Validate composer.json
      run: composer validate --strict

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check MySQL connection
      run: |
        echo "Wait for MySQL to be ready"
        while ! mysqladmin ping -h 127.0.0.1 --silent -u root -prootpassword; do
          sleep 1
        done
        echo "MySQL is up and running"
        
    - name: Install WordPress test suite
      run: bash bin/install-wp-tests.sh wordpress_test root rootpassword 127.0.0.1 latest true

    - name: Run all tests
      run: vendor/bin/phpunit

  lint:
    runs-on: ubuntu-latest
    name: PHP Lint

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl
        tools: cs2pr

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Lint code
      run: composer lint